name: Build and Push Docker Image to ECR

on:
  push:
    branches: [ main ]

env:
 WS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
 AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
 AWS_REGION: ${{ vars.AWS_REGION }}
 PROJECT_NAME: ${{ vars.PROJECT_NAME }}
 MODULE_NAME: ${{ vars.MODULE_NAME }}
 MODULE_FULLNAME: ${{ vars.PROJECT_NAME }}/${{ vars.MODULE_NAME }}
 REGISTRY_URL: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{vars.AWS_REGION }}.amazonaws.com
 TAG: latest
 STACK_NAME: "64bit Amazon Linux 2 v3.5.7 running Docker"

jobs:
  build-and-push:
    runs-on: ubuntu-latest     

    steps:
       - name: Setup node
       - uses: actions/setup-node@v4
       - uses: actions/checkout@v4
         with: 
           node-version: '18'
           cache: 'npm'

       - name: Run Docker build
       - run: docker build -t $MODULE_FULLNAME $MODULE_NAME

       - name: Apply tag
       - run: docker tag $MODULE_FULLNAME:$TAG $REGISTRY_URL/$MODULE_FULLNAME:$TAG

       - name: Auth ECR
       - run: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REGISTRY_URL

       - name: Push image
       - run: docker push $REGISTRY_URL/$MODULE_FULLNAME:$TAG
       - uses: actions/upload-artifact@v4
      

