name: Build and Push Docker Image to ECR

on:
  push:
    branches: [ main ]

env:
 WS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
 AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
 AWS_REGION: ${{ vars.AWS_REGION }}
 PROJECT_NAME: ${{ vars.PROJECT_NAME }}
 MODULE_NAME: ${{ vars.MODULE_NAME }}
 MODULE_FULLNAME: ${{ vars.PROJECT_NAME }}/${{ vars.MODULE_NAME }}
 TAG: latest
 STACK_NAME: "64bit Amazon Linux 2 v3.5.7 running Docker"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: setup node
      uses: actions/setup-node@v4
      with: 
       node-version: '18'
       cache: 'npm'

    - name: Install AWS CLI
      run: |
       curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
       unzip awscliv2.zip
       sudo ./aws/install --update

#    - name: Set up AWS credentials
#     uses: aws-actions/configure-aws-credentials@v1
#      with:
#        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        aws-region: ${{ vars.AWS_REGION }}

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com

    - name: Build Docker image
      run: docker build -t $MODULE_FULLNAME $MODULE_NAME .

    - name: Tag Docker image
      run: docker tag $MODULE_FULLNAME:$TAG $REGISTRY_URL/$MODULE_FULLNAME:$TAG

    - name: Push Docker image to ECR
      run: docker push $REGISTRY_URL/$MODULE_FULLNAME:$TAG
