name: Build and Push Docker Image to ECR

on:
  push:
    branches: [ main ]

env:
 WS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
 AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
 AWS_REGION: ${{ vars.AWS_REGION }}
 PROJECT_NAME: ${{ vars.PROJECT_NAME }}
 MODULE_NAME: ${{ vars.MODULE_NAME }}
 TAG: latest
 STACK_NAME: "64bit Amazon Linux 2 v3.5.7 running Docker"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: setup node
      uses: actions/setup-node@v4
      with: 
       node-version: '18'
       cache: 'npm'

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

    - name: Build Docker image
      run: docker build -t $MODULE_FULLNAME $MODULE_NAME .

    - name: Tag Docker image
      run: docker tag $MODULE_FULLNAME:$TAG $REGISTRY_URL/$MODULE_FULLNAME:$TAG

    - name: Push Docker image to ECR
      run: docker push $REGISTRY_URL/$MODULE_FULLNAME:$TAG
